apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: three-tier
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Make sure this matches the size of the PersistentVolume
  storageClassName: standard  # Ensure this is aligned with the storage class used for PV
