apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-app
  namespace: three-tier
spec:
  project: default
  source:
    repoURL: 'https://github.com/Vishal-Bawa/full-stack-devops-project.git'
    targetRevision: main
    path: k8s
  destination:
    server: https://oidc.eks.ca-central-1.amazonaws.com/id/440B19C8776A32BE66D66580AB271514
    namespace: three-tier
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
